# External on the left, laptop on the right (all positive coords)
monitorrule=name:^HDMI-A-1$,make:Samsung Electric Company,model:LS27D300G,serial:H1AK500000,width:1920,height:1080,refresh:74.97,x:0,y:0,vrr:0
monitorrule=name:^eDP-1$,width:1366,height:768,refresh:60,x:1920,y:
