[garage]
type = s3
provider = Other
access_key_id = GK00a66e850269e3f5b5a71c31
secret_access_key = d5398b91c1758cdc6a542dad6acebc12173fbbbe2e00e195f1088971382b852f
endpoint = https://kenyacares-bucket.prismholdings.co.ke
region = garage
force_path_style = true
