
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2

bind = $mainMod, Period, exec, emote # launch emoji selector // install emote
bind = $mainMod, F12, exec, hyprshade on blue-light-filter # enable blue light filter // install hyprshade
bind = $mainMod, F11, exec, hyprshade off # disable blue light filter // install hyprshade

exec-once = swayidle -w timeout 1200 'swaylock; hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' timeout 1800 'systemctl suspend'

exec-once = 
