global:
  backgroundColor: "#00000000"
  contrastBackgroundColor: "#1A1A1A"
  moreContrastBackgroundColor: "#2A2A2A"
  textColor: "#E5E5E5"
  secondaryTextColor: "#BFBFBF"
  borderColor: "#3A3A3A"
  focusColor: "#8A8A8A"
  titleColor: "#9A9A9A"
  graphicsColor: "#9A9A9A"

welcome:
  formLabelColor: "#BFBFBF"
  formInputColor: "#E5E5E5"
  formInputBackgroundColor: "#1A1A1A"

connection:
  formLabelColor: "#BFBFBF"
  formInputColor: "#E5E5E5"
  formInputBackgroundColor: "#1A1A1A"
  listTextColor: "#D4D4D4"
  listSelectedTextColor: "#0B0B0B"
  listSelectedBackgroundColor: "#8A8A8A"
  listSecondaryTextColor: "#9A9A9A"
  listSecondaryBackgroundColor: "#141414"

header:
  keyColor: "#BFBFBF"
  valueColor: "#9A9A9A"
  activeSymbol: ●
  inactiveSymbol: ○

tabBar:
  activeTextColor: "#0B0B0B"
  activeBackgroundColor: "#8A8A8A"

databases:
  nodeTextColor: "#9A9A9A"
  leafTextColor: "#E5E5E5"
  nodeSymbolColor: "#BFBFBF"
  leafSymbolColor: "#9A9A9A"
  openNodeSymbol: " "
  closedNodeSymbol: " "
  leafSymbol: "󰈙 "

content:
  statusTextColor: "#BFBFBF"
  headerRowColor: "#1A1A1A"
  columnKeyColor: "#BFBFBF"
  columnTypeColor: "#9A9A9A"
  cellTextColor: "#D4D4D4"
  selectedRowColor: "#8A8A8A"
  multiSelectedRowColor: "#5A5A5A"

docPeeker:
  keyColor: "#9A9A9A"
  valueColor: "#E5E5E5"
  bracketColor: "#BFBFBF"
  highlightColor: "#2A2A2A"

inputBar:
  labelColor: "#BFBFBF"
  inputColor: "#E5E5E5"
  autocomplete:
    backgroundColor: "#1A1A1A"
    textColor: "#E5E5E5"
    activeBackgroundColor: "#8A8A8A"
    activeTextColor: "#0B0B0B"
    secondaryTextColor: "#BFBFBF"

history:
  textColor: "#E5E5E5"
  selectedTextColor: "#0B0B0B"
  selectedBackgroundColor: "#8A8A8A"

help:
  headerColor: "#9A9A9A"
  keyColor: "#BFBFBF"
  descriptionColor: "#E5E5E5"

others:
  buttonsTextColor: "#0B0B0B"
  buttonsBackgroundColor: "#8A8A8A"
  deleteButtonSelectedBackgroundColor: "#4A4A4A"
  modalTextColor: "#E5E5E5"
  modalSecondaryTextColor: "#9A9A9A"
  separatorSymbol: "|"
  separatorColor: "#3A3A3A"

styleChange:
  textColor: "#E5E5E5"
  selectedTextColor: "#0B0B0B"
  selectedBackgroundColor: "#8A8A8A"

aiPrompt:
  formLabelColor: "#BFBFBF"
  formInputColor: "#E5E5E5"
  formInputBackgroundColor: "#1A1A1A"
